// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config/data_feed/config_request.proto

package data_feed

import (
	fmt "fmt"
	shared "github.com/chef/automate/api/config/shared"
	_ "github.com/chef/automate/components/automate-grpc/protoc-gen-a2-config/api/a2conf"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConfigRequest struct {
	V1                   *ConfigRequest_V1 `protobuf:"bytes,1,opt,name=v1,proto3" json:"v1,omitempty" toml:"v1,omitempty" mapstructure:"v1,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte            `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32             `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *ConfigRequest) Reset()         { *m = ConfigRequest{} }
func (m *ConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigRequest) ProtoMessage()    {}
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3242a03f842acaa1, []int{0}
}

func (m *ConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRequest.Unmarshal(m, b)
}
func (m *ConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRequest.Marshal(b, m, deterministic)
}
func (m *ConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRequest.Merge(m, src)
}
func (m *ConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigRequest.Size(m)
}
func (m *ConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRequest proto.InternalMessageInfo

func (m *ConfigRequest) GetV1() *ConfigRequest_V1 {
	if m != nil {
		return m.V1
	}
	return nil
}

type ConfigRequest_V1 struct {
	Sys                  *ConfigRequest_V1_System `protobuf:"bytes,1,opt,name=sys,proto3" json:"sys,omitempty" toml:"sys,omitempty" mapstructure:"sys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte                   `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32                    `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *ConfigRequest_V1) Reset()         { *m = ConfigRequest_V1{} }
func (m *ConfigRequest_V1) String() string { return proto.CompactTextString(m) }
func (*ConfigRequest_V1) ProtoMessage()    {}
func (*ConfigRequest_V1) Descriptor() ([]byte, []int) {
	return fileDescriptor_3242a03f842acaa1, []int{0, 0}
}

func (m *ConfigRequest_V1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRequest_V1.Unmarshal(m, b)
}
func (m *ConfigRequest_V1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRequest_V1.Marshal(b, m, deterministic)
}
func (m *ConfigRequest_V1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRequest_V1.Merge(m, src)
}
func (m *ConfigRequest_V1) XXX_Size() int {
	return xxx_messageInfo_ConfigRequest_V1.Size(m)
}
func (m *ConfigRequest_V1) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRequest_V1.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRequest_V1 proto.InternalMessageInfo

func (m *ConfigRequest_V1) GetSys() *ConfigRequest_V1_System {
	if m != nil {
		return m.Sys
	}
	return nil
}

type ConfigRequest_V1_System struct {
	Mlsa                 *shared.Mlsa                     `protobuf:"bytes,1,opt,name=mlsa,proto3" json:"mlsa,omitempty" toml:"mlsa,omitempty" mapstructure:"mlsa,omitempty"`
	Tls                  *shared.TLSCredentials           `protobuf:"bytes,2,opt,name=tls,proto3" json:"tls,omitempty" toml:"tls,omitempty" mapstructure:"tls,omitempty"`
	Service              *ConfigRequest_V1_System_Service `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty" toml:"service,omitempty" mapstructure:"service,omitempty"`
	Log                  *ConfigRequest_V1_System_Log     `protobuf:"bytes,4,opt,name=log,proto3" json:"log,omitempty" toml:"log,omitempty" mapstructure:"log,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte                           `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32                            `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *ConfigRequest_V1_System) Reset()         { *m = ConfigRequest_V1_System{} }
func (m *ConfigRequest_V1_System) String() string { return proto.CompactTextString(m) }
func (*ConfigRequest_V1_System) ProtoMessage()    {}
func (*ConfigRequest_V1_System) Descriptor() ([]byte, []int) {
	return fileDescriptor_3242a03f842acaa1, []int{0, 0, 0}
}

func (m *ConfigRequest_V1_System) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRequest_V1_System.Unmarshal(m, b)
}
func (m *ConfigRequest_V1_System) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRequest_V1_System.Marshal(b, m, deterministic)
}
func (m *ConfigRequest_V1_System) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRequest_V1_System.Merge(m, src)
}
func (m *ConfigRequest_V1_System) XXX_Size() int {
	return xxx_messageInfo_ConfigRequest_V1_System.Size(m)
}
func (m *ConfigRequest_V1_System) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRequest_V1_System.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRequest_V1_System proto.InternalMessageInfo

func (m *ConfigRequest_V1_System) GetMlsa() *shared.Mlsa {
	if m != nil {
		return m.Mlsa
	}
	return nil
}

func (m *ConfigRequest_V1_System) GetTls() *shared.TLSCredentials {
	if m != nil {
		return m.Tls
	}
	return nil
}

func (m *ConfigRequest_V1_System) GetService() *ConfigRequest_V1_System_Service {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *ConfigRequest_V1_System) GetLog() *ConfigRequest_V1_System_Log {
	if m != nil {
		return m.Log
	}
	return nil
}

type ConfigRequest_V1_System_Service struct {
	Host                 *wrappers.StringValue  `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty" toml:"host,omitempty" mapstructure:"host,omitempty"`
	Port                 *wrappers.Int32Value   `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty" toml:"port,omitempty" mapstructure:"port,omitempty"`
	FeedInterval         *wrappers.StringValue  `protobuf:"bytes,3,opt,name=feed_interval,json=feedInterval,proto3" json:"feed_interval,omitempty" toml:"feed_interval,omitempty" mapstructure:"feed_interval,omitempty"`
	AssetPageSize        *wrappers.Int32Value   `protobuf:"bytes,4,opt,name=asset_page_size,json=assetPageSize,proto3" json:"asset_page_size,omitempty" toml:"asset_page_size,omitempty" mapstructure:"asset_page_size,omitempty"`
	ReportsPageSize      *wrappers.Int32Value   `protobuf:"bytes,5,opt,name=reports_page_size,json=reportsPageSize,proto3" json:"reports_page_size,omitempty" toml:"reports_page_size,omitempty" mapstructure:"reports_page_size,omitempty"`
	NodeBatchSize        *wrappers.Int32Value   `protobuf:"bytes,6,opt,name=node_batch_size,json=nodeBatchSize,proto3" json:"node_batch_size,omitempty" toml:"node_batch_size,omitempty" mapstructure:"node_batch_size,omitempty"`
	UpdatedNodesOnly     *wrappers.BoolValue    `protobuf:"bytes,7,opt,name=updated_nodes_only,json=updatedNodesOnly,proto3" json:"updated_nodes_only,omitempty" toml:"updated_nodes_only,omitempty" mapstructure:"updated_nodes_only,omitempty"`
	DisableCidrFilter    *wrappers.BoolValue    `protobuf:"bytes,8,opt,name=disable_cidr_filter,json=disableCidrFilter,proto3" json:"disable_cidr_filter,omitempty" toml:"disable_cidr_filter,omitempty" mapstructure:"disable_cidr_filter,omitempty"`
	CidrFilter           *wrappers.StringValue  `protobuf:"bytes,9,opt,name=cidr_filter,json=cidrFilter,proto3" json:"cidr_filter,omitempty" toml:"cidr_filter,omitempty" mapstructure:"cidr_filter,omitempty"`
	ExternalFqdn         *wrappers.StringValue  `protobuf:"bytes,10,opt,name=external_fqdn,json=externalFqdn,proto3" json:"external_fqdn,omitempty" toml:"external_fqdn,omitempty" mapstructure:"external_fqdn,omitempty"`
	AcceptedStatusCodes  []*wrappers.Int32Value `protobuf:"bytes,11,rep,name=accepted_status_codes,json=acceptedStatusCodes,proto3" json:"accepted_status_codes,omitempty" toml:"accepted_status_codes,omitempty" mapstructure:"accepted_status_codes,omitempty"`
	ContentType          *wrappers.StringValue  `protobuf:"bytes,12,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty" toml:"content_type,omitempty" mapstructure:"content_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte                 `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32                  `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *ConfigRequest_V1_System_Service) Reset()         { *m = ConfigRequest_V1_System_Service{} }
func (m *ConfigRequest_V1_System_Service) String() string { return proto.CompactTextString(m) }
func (*ConfigRequest_V1_System_Service) ProtoMessage()    {}
func (*ConfigRequest_V1_System_Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_3242a03f842acaa1, []int{0, 0, 0, 0}
}

func (m *ConfigRequest_V1_System_Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRequest_V1_System_Service.Unmarshal(m, b)
}
func (m *ConfigRequest_V1_System_Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRequest_V1_System_Service.Marshal(b, m, deterministic)
}
func (m *ConfigRequest_V1_System_Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRequest_V1_System_Service.Merge(m, src)
}
func (m *ConfigRequest_V1_System_Service) XXX_Size() int {
	return xxx_messageInfo_ConfigRequest_V1_System_Service.Size(m)
}
func (m *ConfigRequest_V1_System_Service) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRequest_V1_System_Service.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRequest_V1_System_Service proto.InternalMessageInfo

func (m *ConfigRequest_V1_System_Service) GetHost() *wrappers.StringValue {
	if m != nil {
		return m.Host
	}
	return nil
}

func (m *ConfigRequest_V1_System_Service) GetPort() *wrappers.Int32Value {
	if m != nil {
		return m.Port
	}
	return nil
}

func (m *ConfigRequest_V1_System_Service) GetFeedInterval() *wrappers.StringValue {
	if m != nil {
		return m.FeedInterval
	}
	return nil
}

func (m *ConfigRequest_V1_System_Service) GetAssetPageSize() *wrappers.Int32Value {
	if m != nil {
		return m.AssetPageSize
	}
	return nil
}

func (m *ConfigRequest_V1_System_Service) GetReportsPageSize() *wrappers.Int32Value {
	if m != nil {
		return m.ReportsPageSize
	}
	return nil
}

func (m *ConfigRequest_V1_System_Service) GetNodeBatchSize() *wrappers.Int32Value {
	if m != nil {
		return m.NodeBatchSize
	}
	return nil
}

func (m *ConfigRequest_V1_System_Service) GetUpdatedNodesOnly() *wrappers.BoolValue {
	if m != nil {
		return m.UpdatedNodesOnly
	}
	return nil
}

func (m *ConfigRequest_V1_System_Service) GetDisableCidrFilter() *wrappers.BoolValue {
	if m != nil {
		return m.DisableCidrFilter
	}
	return nil
}

func (m *ConfigRequest_V1_System_Service) GetCidrFilter() *wrappers.StringValue {
	if m != nil {
		return m.CidrFilter
	}
	return nil
}

func (m *ConfigRequest_V1_System_Service) GetExternalFqdn() *wrappers.StringValue {
	if m != nil {
		return m.ExternalFqdn
	}
	return nil
}

func (m *ConfigRequest_V1_System_Service) GetAcceptedStatusCodes() []*wrappers.Int32Value {
	if m != nil {
		return m.AcceptedStatusCodes
	}
	return nil
}

func (m *ConfigRequest_V1_System_Service) GetContentType() *wrappers.StringValue {
	if m != nil {
		return m.ContentType
	}
	return nil
}

type ConfigRequest_V1_System_Log struct {
	Format               *wrappers.StringValue `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty" toml:"format,omitempty" mapstructure:"format,omitempty"`
	Level                *wrappers.StringValue `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty" toml:"level,omitempty" mapstructure:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_unrecognized     []byte                `json:"-" toml:"-" mapstructure:"-,omitempty"`
	XXX_sizecache        int32                 `json:"-" toml:"-" mapstructure:"-,omitempty"`
}

func (m *ConfigRequest_V1_System_Log) Reset()         { *m = ConfigRequest_V1_System_Log{} }
func (m *ConfigRequest_V1_System_Log) String() string { return proto.CompactTextString(m) }
func (*ConfigRequest_V1_System_Log) ProtoMessage()    {}
func (*ConfigRequest_V1_System_Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_3242a03f842acaa1, []int{0, 0, 0, 1}
}

func (m *ConfigRequest_V1_System_Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRequest_V1_System_Log.Unmarshal(m, b)
}
func (m *ConfigRequest_V1_System_Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRequest_V1_System_Log.Marshal(b, m, deterministic)
}
func (m *ConfigRequest_V1_System_Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRequest_V1_System_Log.Merge(m, src)
}
func (m *ConfigRequest_V1_System_Log) XXX_Size() int {
	return xxx_messageInfo_ConfigRequest_V1_System_Log.Size(m)
}
func (m *ConfigRequest_V1_System_Log) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRequest_V1_System_Log.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRequest_V1_System_Log proto.InternalMessageInfo

func (m *ConfigRequest_V1_System_Log) GetFormat() *wrappers.StringValue {
	if m != nil {
		return m.Format
	}
	return nil
}

func (m *ConfigRequest_V1_System_Log) GetLevel() *wrappers.StringValue {
	if m != nil {
		return m.Level
	}
	return nil
}

func init() {
	proto.RegisterType((*ConfigRequest)(nil), "chef.automate.domain.data_feed.ConfigRequest")
	proto.RegisterType((*ConfigRequest_V1)(nil), "chef.automate.domain.data_feed.ConfigRequest.V1")
	proto.RegisterType((*ConfigRequest_V1_System)(nil), "chef.automate.domain.data_feed.ConfigRequest.V1.System")
	proto.RegisterType((*ConfigRequest_V1_System_Service)(nil), "chef.automate.domain.data_feed.ConfigRequest.V1.System.Service")
	proto.RegisterType((*ConfigRequest_V1_System_Log)(nil), "chef.automate.domain.data_feed.ConfigRequest.V1.System.Log")
}

func init() {
	proto.RegisterFile("config/data_feed/config_request.proto", fileDescriptor_3242a03f842acaa1)
}

var fileDescriptor_3242a03f842acaa1 = []byte{
	// 727 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0xed, 0x4e, 0xeb, 0x36,
	0x18, 0xc7, 0x45, 0x5b, 0xca, 0x70, 0xa9, 0x00, 0xa3, 0x8d, 0x28, 0x9b, 0x10, 0x9a, 0x34, 0x69,
	0x9a, 0xd4, 0x84, 0x16, 0xa4, 0x49, 0x7b, 0x11, 0xa3, 0x95, 0x60, 0x4c, 0x30, 0xa6, 0x14, 0x21,
	0x6d, 0x5f, 0x22, 0x37, 0x79, 0x92, 0x5a, 0x72, 0xed, 0x60, 0xbb, 0xdd, 0x29, 0xf7, 0x72, 0xee,
	0xe1, 0x9c, 0x5b, 0x40, 0xe7, 0x3a, 0xce, 0x4d, 0x70, 0x03, 0x47, 0x76, 0x5c, 0x0e, 0x2f, 0x52,
	0xe9, 0xe1, 0x63, 0x62, 0xff, 0x7e, 0x79, 0xfc, 0xb7, 0x1f, 0x07, 0xfd, 0x90, 0x08, 0x9e, 0xd1,
	0x3c, 0x4c, 0x89, 0x26, 0x71, 0x06, 0x90, 0x86, 0xe5, 0x8b, 0x58, 0xc2, 0xf5, 0x18, 0x94, 0x0e,
	0x0a, 0x29, 0xb4, 0xc0, 0x3b, 0xc9, 0x10, 0xb2, 0x80, 0x8c, 0xb5, 0x18, 0x11, 0x0d, 0x41, 0x2a,
	0x46, 0x84, 0xf2, 0xe0, 0x1e, 0xf2, 0x7d, 0xa7, 0x51, 0x43, 0x22, 0x21, 0x0d, 0x73, 0x26, 0x06,
	0x84, 0x95, 0xac, 0xbf, 0xfd, 0x78, 0x4c, 0x33, 0xe5, 0x06, 0x0e, 0x67, 0xbe, 0x56, 0x2e, 0x8b,
	0x24, 0xb4, 0x2f, 0x93, 0x56, 0x0e, 0xbc, 0x45, 0x3a, 0x2d, 0x07, 0x91, 0x82, 0x86, 0xa4, 0x63,
	0x1e, 0x42, 0xc2, 0xb9, 0xd0, 0x44, 0x53, 0xc1, 0x67, 0x82, 0x9d, 0x5c, 0x88, 0x9c, 0x41, 0x49,
	0x0e, 0xc6, 0x59, 0xf8, 0xbf, 0x24, 0x45, 0x01, 0xd2, 0x8d, 0x7f, 0xff, 0xb6, 0x81, 0x9a, 0x3d,
	0xeb, 0x89, 0xca, 0xd5, 0xe0, 0x3f, 0x50, 0x65, 0xd2, 0xf6, 0x96, 0x76, 0x97, 0x7e, 0x6c, 0x74,
	0xf6, 0x82, 0xf9, 0x8b, 0x0a, 0x1e, 0xa1, 0xc1, 0x55, 0x3b, 0xaa, 0x4c, 0xda, 0xfe, 0x3b, 0x84,
	0x2a, 0x57, 0x6d, 0x7c, 0x8a, 0xaa, 0x6a, 0xaa, 0x9c, 0xe9, 0xe7, 0x2f, 0x35, 0x05, 0xfd, 0xa9,
	0xd2, 0x30, 0x8a, 0x8c, 0xc3, 0xff, 0xb8, 0x8a, 0xea, 0xe5, 0x33, 0x3e, 0x40, 0xb5, 0x11, 0x53,
	0xc4, 0x69, 0x77, 0x9f, 0x68, 0x29, 0xcf, 0x24, 0x09, 0xca, 0x60, 0x82, 0x73, 0xa6, 0x48, 0x64,
	0x67, 0xe3, 0xdf, 0x50, 0x55, 0x33, 0xe5, 0x55, 0x2c, 0xf4, 0xd3, 0x3c, 0xe8, 0xf2, 0xac, 0xdf,
	0x93, 0x90, 0x02, 0xd7, 0x94, 0x30, 0x15, 0x19, 0x0c, 0xff, 0x8b, 0x56, 0x14, 0xc8, 0x09, 0x4d,
	0xc0, 0xab, 0x5a, 0xc3, 0xe1, 0x2b, 0x57, 0x13, 0xf4, 0x4b, 0x4d, 0x34, 0xf3, 0xe1, 0x73, 0x54,
	0x65, 0x22, 0xf7, 0x6a, 0x56, 0xfb, 0xeb, 0x6b, 0xb5, 0x67, 0x22, 0x8f, 0x8c, 0xc7, 0xff, 0x50,
	0x47, 0x2b, 0xee, 0x1b, 0x78, 0x0f, 0xd5, 0x86, 0x42, 0x69, 0x97, 0xd4, 0x77, 0x41, 0x79, 0x12,
	0x82, 0xd9, 0x49, 0x08, 0xfa, 0x5a, 0x52, 0x9e, 0x5f, 0x11, 0x36, 0x86, 0xc8, 0xce, 0xc4, 0x27,
	0xa8, 0x56, 0x08, 0xa9, 0x5d, 0x4c, 0xdf, 0x3e, 0x23, 0x4e, 0xb9, 0xde, 0xef, 0x58, 0xa0, 0xfb,
	0xcd, 0xed, 0x9d, 0x87, 0xef, 0x63, 0xd9, 0x78, 0x3f, 0xf2, 0x6b, 0xe6, 0x84, 0x46, 0x56, 0x80,
	0x8f, 0x50, 0xd3, 0xd4, 0x1b, 0x53, 0xae, 0x41, 0x4e, 0x08, 0x73, 0xb1, 0xcd, 0xaf, 0x61, 0xcd,
	0x20, 0xa7, 0x8e, 0xc0, 0x3d, 0xb4, 0x4e, 0x94, 0x02, 0x1d, 0x17, 0x24, 0x87, 0x58, 0xd1, 0x1b,
	0x70, 0x21, 0xcd, 0x2b, 0x2b, 0x6a, 0x5a, 0xe6, 0x1f, 0x92, 0x43, 0x9f, 0xde, 0x00, 0x3e, 0x41,
	0x9b, 0x12, 0x4c, 0x45, 0xea, 0x81, 0x66, 0xf9, 0x65, 0xcd, 0xba, 0xa3, 0xee, 0x45, 0x3d, 0xb4,
	0xce, 0x45, 0x0a, 0xf1, 0x80, 0xe8, 0x64, 0x58, 0x6a, 0xea, 0x0b, 0x54, 0x63, 0x98, 0xae, 0x41,
	0xac, 0xe4, 0x4f, 0x84, 0xc7, 0x45, 0x4a, 0x34, 0xa4, 0xb1, 0x19, 0x50, 0xb1, 0xe0, 0x6c, 0xea,
	0xad, 0x58, 0x8f, 0xff, 0xcc, 0xd3, 0x15, 0x82, 0x95, 0x9a, 0x0d, 0x47, 0xfd, 0x6d, 0xa0, 0x0b,
	0xce, 0xa6, 0xf8, 0x2f, 0xb4, 0x95, 0x52, 0x45, 0x06, 0x0c, 0xe2, 0x84, 0xa6, 0x32, 0xce, 0x28,
	0xd3, 0x20, 0xbd, 0xaf, 0x5e, 0x54, 0x6d, 0x3a, 0xac, 0x47, 0x53, 0x79, 0x6c, 0x21, 0xfc, 0x3b,
	0x6a, 0x3c, 0x74, 0xac, 0x2e, 0xb0, 0x53, 0x28, 0xf9, 0x8c, 0x1f, 0xa1, 0x26, 0xbc, 0xd1, 0x20,
	0x39, 0x61, 0x71, 0x76, 0x9d, 0x72, 0x0f, 0x2d, 0xb2, 0xd5, 0x33, 0xe4, 0xf8, 0x3a, 0xe5, 0xf8,
	0x02, 0x7d, 0x4d, 0x92, 0x04, 0x0a, 0x13, 0x8c, 0xd2, 0x44, 0x8f, 0x55, 0x9c, 0x98, 0xa5, 0x7a,
	0x8d, 0xdd, 0xea, 0x4b, 0x11, 0x6f, 0xcd, 0xc8, 0xbe, 0x05, 0x7b, 0x86, 0xc3, 0x87, 0x68, 0x2d,
	0x11, 0x5c, 0x03, 0xd7, 0xb1, 0x9e, 0x16, 0xe0, 0xad, 0x2d, 0x50, 0x52, 0xc3, 0x11, 0x97, 0xd3,
	0x02, 0x7c, 0x81, 0xaa, 0x67, 0x22, 0xc7, 0x07, 0xa8, 0x9e, 0x09, 0x39, 0x22, 0x8b, 0xf5, 0x90,
	0x9b, 0x8b, 0x3b, 0x68, 0x99, 0xc1, 0x04, 0x98, 0x6b, 0xa3, 0xf9, 0x50, 0x39, 0xf5, 0x97, 0xed,
	0xdb, 0x3b, 0x6f, 0x0b, 0x6d, 0x9a, 0x4e, 0x6f, 0x99, 0x36, 0x68, 0xb9, 0xc6, 0xea, 0x86, 0xff,
	0xb5, 0x72, 0xaa, 0x87, 0xe3, 0x41, 0x90, 0x88, 0x51, 0x68, 0xae, 0x87, 0x70, 0x76, 0x3d, 0xd8,
	0x8b, 0xff, 0xe9, 0xbf, 0x69, 0x50, 0xb7, 0x9f, 0xd9, 0xff, 0x14, 0x00, 0x00, 0xff, 0xff, 0x4f,
	0x7b, 0x89, 0xeb, 0xb6, 0x06, 0x00, 0x00,
}
